spring:
  datasource:
    url: jdbc:mysql://192.168.1.200:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: test
    password: 123456

logging:
  level:
    cn.tedu.csmall: debug